# Generated by Django 2.2.7 on 2021-10-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_reveiew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
